#!/usr/bin/env python3
""" Factor numbers """

from sys import argv
from math import sqrt

def open_read_file(file_name):
    """read from file
    add to array
    """
    with open(file_name, "r", encoding="utf-8") as file:
        lines = file.readlines()
    return [int(line.strip()) for line in lines]

def find_and_print_factors(n):
    """Factor the given number n."""
    for j in range(2, int(sqrt(n)) + 1):
        if n % j == 0:
            print(f"{n}={n // j}*{j}")
            return
    print(f"{n}=1*{n}")  # If no factors were found (n is prime)

def factorize_numbers(numbers):
    """Factor each number in the list."""
    for number in numbers:
        find_and_print_factors(number)

if len(argv) == 2:
    numbers = open_read_file(argv[1])
    factorize_numbers(numbers)
